############################################################
#
# Copyright (c) 1992 Twenty-First Designs, Inc.
# Unpublished work. All rights reserved.  
#
# THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF 
# TWENTY-FIRST DESIGNS, INC.
#
# This software source code contains trade secrets and other
# proprietary information of Twenty-First Designs, Inc. All
# disclosure or use of this source code is strictly restricted
# by contract to that required for operation and maintenance 
# of equipment provided by Twenty-First Designs, Inc.
# All other disclosure or use of this source code is prohibited.
#
###########################################################
#
# $Id: Makefile,v 1.1.1.1 2000/10/18 04:29:56 kent Exp $
#
###########################################################
#
# Makefile for Toll Switch Z80 ZOS Softare
#
###########################################################

SUBDIRS	=
DESTDIR	=

SMN  = ../../src.m68k

include	$(SMN)/conf/smn_lib.mk

clean::; $(RM) make.log install.log


